server:
  port: 8098
spring:
  application:
    name: spring-boot-health

info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@