server:
  port: 9000
spring:
  application:
    name: feign-consumer
eureka:
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



