server:
  port: 8766
eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://peer2:8769/eureka,http://peer1:8761/eureka
spring:
  application:
    name: eureka-server-peer3