server:
  port: 8769
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka,http://peer3:8766/eureka
spring:
  application:
    name: eureka-server-peer2