spring:
  rabbitmq:
    addresses: localhost
    port: 5762
  application:
    name: config-client
  cloud:
    config:
      uri: http://localhost:8888/
      profile: dev
      label: master
server:
  port: 8882