server:
  port: 8090
  #context-path: /boot-admin
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

spring:
  application:
    name: boot-admin
  boot:
    admin:
      #url: http://localhost:8090
      context-path: /sba

management.security.enabled: false
security:
  basic:
    enabled: false

